baseURL = ""
languageCode = "en-us"
title = "HatchLatch®"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "FAQ"
        url     = "/faq"
        weight  = 2
    [[menu.nav]]
        name    = "Downloads"
        url     = "/downloads"
        weight  = 3        
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 4
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 5

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    # logo = "images/logo.png"
    # logo_alt = "logo"
    logo_text = "HatchLatch®"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/hatch_latch_IV_big.jpg"
        heading = "HatchLatch® IV DOOR RESTRICTOR"
        description = "Creating a safer passenger environment—and reducing your labor costs—just got a little easier."
        btn     = true
        btnText = "Buy Now at ADAMS Elevator"
        btnURL  = "https://shop.adamselevator.com/"
        [[params.banner.flipText]]
            title   = "Safe"
        [[params.banner.flipText]]
            title   = "Reliable"
        [[params.banner.flipText]]
            title   = "Intelligent"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "Safety Simplified. Introducing The New, Easier-To-Install HatchLatch®IV."
        content = "Our new and improved HatchLatch® IV—the leading choice in electronic door restrictors—now requires only one optical sensor. This new design significantly reduces installation time and complexity, while an improved solenoid control assembly boosts overall performance and reliability."
        image   = "images/A835A4.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "HAVE QUESTIONS ?"
        content = "Check out our frequently asked questions for the answers to your questions."
        btnText = "F.A.Q."
        btnURL  = "/faq"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= ""

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= ""

    # Footer section
    [params.footer]
        customized  = true # Set this variable to true if you customized the design.
        copyright_owner = "Advanced Microcontrols Inc"
        copyright_since = "2018"
        # [[params.footer.social]]
        #     icon = "ion-social-facebook"
        #     link = "https://facebook.com"
        # [[params.footer.social]]
        #     icon = "ion-social-twitter"
        #     link = "https://twitter.com"
        # [[params.footer.social]]
        #     icon = "ion-social-linkedin"
        #     link = "https://linkedin.com"
        # [[params.footer.social]]
        #     icon = "ion-social-googleplus"
        #     link = "https://googleplus.com"
        # [[params.footer.social]]
        #     icon = "ion-social-github"
        #     link = "https://github.com"
    